[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "psx-data"
version = "0.2.0"
description = "A zero-dependency Python library for collecting, parsing, and working with data from the Pakistan Stock Exchange."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Yasir W." }
]

[project.urls]
Repository = "https://github.com/yasir-a/psx-data"
Issues = "https://github.com/yasir-a/psx-data/issues"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
psx-data = "psx_data.cli:main"